pipeline {
    agent any


    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/rajeevgithub007/Development.git'
            }
        }
        stage('Install Make') {
            steps {
                script {
                    sh 'sudo apt-get update && sudo apt-get install -y make'

                }

            }
        }
        stage('Provisioning') {
            steps {
                script {
                    nodejs('Node-18.14.1') {
                     sh 'node -v'
                     sh 'yarn install'
                    }
                    // dir('../') {
                    //     // Run the 'make' command
                    //     sh 'make'
                    // }
                }
                echo 'Provisioning Jenkinsfile - Provisioning job is working'
            }
        }
    }
}
