pipeline {
    agent any

    stages {
        stage('Provisioning') {
            steps {
                script {
                    dir('../')
                    sh 'make'
                }
                echo 'Provisioning Jenkinsfile - Provisioning job is working'
            }
        }
    }
}
