pipeline {
    agent any

    stages {
        stage('Provisioning') {
            steps {
                script {
                    dir('../') {
                        // Run the 'make' command
                        sh 'make'
                    }
                }
                echo 'Provisioning Jenkinsfile - Provisioning job is working'
            }
        }
    }
}
